# Python CircleCI 2.0 configuration file
# vi: et:ts=2:sw=2
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.14-stretch
    working_directory: ~/python-mbedtls
    steps:
      - checkout
      - run:
          name: install pyenv
          command: |
            git clone https://github.com/pyenv/pyenv.git $HOME/python-mbedtls/.pyenv
            cat << 'EOF' >> $BASH_ENV
            export PYENV_ROOT="$HOME/python-mbedtls/.pyenv"
            export PATH="$PYENV_ROOT/bin:$PATH"
            EOF

      - restore_cache:
          keys:
            - py27-v1-{{ arch }}-2.7.15
      - run:
          name: install python 2.7
          command: |
            if [ ! -d ".pyenv/versions/2.7.15" ]; then
              eval "$(pyenv init -)"
              pyenv install 2.7.15
            fi
      - save_cache:
          key: py27-v1-{{ arch }}-2.7.15
          paths:
            - .pyenv/versions/2.7.15

      - restore_cache:
          keys:
            - py34-v1-{{ arch }}-3.4.8
      - run:
          name: install python 3.4
          command: |
            if [ ! -d ".pyenv/versions/3.4.8" ]; then
              eval "$(pyenv init -)"
              pyenv install 3.4.8
            fi
      - save_cache:
          key: py34-v1-{{ arch }}-3.4.8
          paths:
            - .pyenv/versions/3.4.8

      - restore_cache:
          keys:
            - py35-v1-{{ arch }}-3.5.5
      - run:
          name: install python 3.5
          command: |
            if [ ! -d ".pyenv/versions/3.5.5" ]; then
              eval "$(pyenv init -)"
              pyenv install 3.5.5
            fi
      - save_cache:
          key: py35-v1-{{ arch }}-3.5.5
          paths:
            - .pyenv/versions/3.5.5

      - restore_cache:
          keys:
            - py36-v1-{{ arch }}-3.6.5
      - run:
          name: install python 3.6
          command: |
            if [ ! -d ".pyenv/versions/3.6.5" ]; then
              eval "$(pyenv init -)"
              pyenv install 3.6.5
            fi
      - save_cache:
          key: py36-v1-{{ arch }}-3.6.5
          paths:
            - .pyenv/versions/3.6.5

      - run:
          name: setup environment
          command: |
            cat << 'EOF' >> $BASH_ENV
            export VERSION=2.4.2
            export DESTDIR=$HOME/lib/mbedtls-$VERSION
            export LIBRARY_PATH=$DESTDIR/lib
            export LD_LIBRARY_PATH=$DESTDIR/lib
            export C_INCLUDE_PATH=$DESTDIR/include
            EOF
      - run:
          name: install mbedtls
          command: |
            echo 'deb http://deb.debian.org/debian jessie-backports main' |\
              sudo tee /etc/apt/sources.list.d/backports.list
            sudo apt-get update
            sudo apt-get install libmbedtls-dev

      - restore_cache:
          keys:
            - py-deps-2.7-{{ checksum "requirements-tests.txt" }}
      - run:
          name: install environment
          command: |
            sudo apt-get install python-virtualenv
            python -m virtualenv venv
            . venv/bin/activate
            pip install -r requirements-tests.txt
      - save_cache:
          key: py-deps-2.7-{{ checksum "requirements-tests.txt" }}
          paths:
            - venv

      - run:
          name: run tests
          command: |
            eval "$(pyenv init -)"
            pyenv shell 2.7.15 3.4.8 3.5.5 3.6.5
            . venv/bin/activate
            detox

      - deploy:
          name: Publish to Pypi
          command: |
            if [ "$CIRCLE_BRANCH" = "master" ]; then
              echo "[pypi]" > $HOME/.pypirc
              echo "username = Synss" >> $HOME/.pypirc
              echo "password = $PYPI_PASSWORD" >> $HOME/.pypirc
              . venv/bin/activate
              python setup.py sdist
              twine upload dist/*
            fi

      - run:
          name: save logs
          command: |
            mkdir -p out/log
            cp .tox/*/log/py*.log out/log || true
          when: on_fail

      - run:
          name: save dist
          command: |
            mkdir -p out/dist
            cp dist/* out/dist
          when: on_success

      - store_artifacts:
          path: out
          destination: artifacts
